<?php
/**
 * Cybage Marketplace Plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * It is available on the World Wide Web at:
 * http://opensource.org/licenses/osl-3.0.php
 * If you are unable to access it on the World Wide Web, please send an email
 * To: Support_Magento@cybage.com.  We will send you a copy of the source file.
 *
 * @category   Marketplace Plugin
 * @package    Cybage_Marketplace
 * @copyright  Copyright (c) 2014 Cybage Software Pvt. Ltd., India
 *             http://www.cybage.com/pages/centers-of-excellence/ecommerce/ecommerce.aspx
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Cybage Software Pvt. Ltd. <Support_Magento@cybage.com>
 */

if ($this->getData('url') != '')
    echo '<a id="askquestion" href="' . $this->getData('url') . '">Ask Question</a>';
?>
<script type="text/javascript">
    jQuery(document).ready(function() {
    jQuery("#askquestion").fancybox({
             maxWidth    : '70%',
    maxHeight   : 365,
    fitToView   : true,
    width       : '70%',
    height      : 365,
    autoSize    : true,
    closeClick  : true,
    openEffect  : 'elastic',
    closeEffect : 'elastic',
    autoDimensions  : true,
    scrolling   : 'no'
            });
    });
</script>