<?php

/**

 * Cybage Marketplace Plugin

 *

 * NOTICE OF LICENSE

 *

 * This source file is subject to the Open Software License (OSL 3.0)

 * It is available on the World Wide Web at:

 * http://opensource.org/licenses/osl-3.0.php

 * If you are unable to access it on the World Wide Web, please send an email

 * To: Support_Magento@cybage.com.  We will send you a copy of the source file.

 *

 * @category   Marketplace Plugin

 * @package    Cybage_Marketplace

 * @copyright  Copyright (c) 2014 Cybage Software Pvt. Ltd., India

 *             http://www.cybage.com/pages/centers-of-excellence/ecommerce/ecommerce.aspx

 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)

 * @author     Cybage Software Pvt. Ltd. <Support_Magento@cybage.com>

 */

?>

<!--<script type="text/javascript">bkLib.onDomLoaded(nicEditors.allTextAreas);</script>-->

<div class="page-title">

    <h1><?php echo $this->__('Edit Account Information') ?></h1>

</div>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" enctype="multipart/form-data" id="form-validate" autocomplete="off">

    <div class="fieldset">

        <?php echo $this->getBlockHtml('formkey')?>

        <h2 class="legend"><?php echo $this->__('Account Information') ?></h2>

        <ul class="form-list">

            <li class="fields">

                <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml() ?>

            </li>

            <li>

                <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>

                <div class="input-box">

                    <input type="text" name="email" id="email" value="<?php echo $this->escapeHtml($this->getCustomer()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text required-entry validate-email" />

                </div>

            </li>
            
             <li>

                <label for="profileimage-file"><?php echo $this->__('Image') ?></label>

                <div class="input-box">

                <input id="file" type="file" name="profileimage-file">

                </div>

            </li>
            
            

        <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>

        <?php if ($_dob->isEnabled()): ?>

            <li><?php echo $_dob->setDate($this->getCustomer()->getDob())->toHtml() ?></li>

        <?php endif ?>

        <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>

        <?php if ($_taxvat->isEnabled()): ?>

            <li><?php echo $_taxvat->setTaxvat($this->getCustomer()->getTaxvat())->toHtml() ?></li>

        <?php endif ?>

        <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>

        <?php if ($_gender->isEnabled()): ?>

            <li><?php echo $_gender->setGender($this->getCustomer()->getGender())->toHtml() ?></li>

        <?php endif ?>

            <li class="control">

                <input type="checkbox" name="change_password" id="change_password" value="1" onclick="setPasswordForm(this.checked)" title="<?php echo $this->__('Change Password') ?>"<?php if($this->getCustomer()->getChangePassword()==1): ?> checked="checked"<?php endif; ?> class="checkbox" /><label for="change_password"><?php echo $this->__('Change Password') ?></label>

            </li>

            <?php $isMarketplaceEnabled=Mage::Helper("marketplace")->isMarketplaceEnabled(); ?>

            <?php if($isMarketplaceEnabled):?>

                <!--begining of Add seller profile form-->

                <?php $isSeller = $this->getCustomer()->getSellerSubscriber(); ?>

                    

                <?php if($isSeller == 0):?>
<?php if (Mage::getSingleton('customer/session')->isLoggedIn()==0): ?>

<?php else: ?>
<?php
				$customer = Mage::getSingleton('customer/session')->getCustomer();
 $zz=   $customer->getCompanyName(); // Full Name
if($zz!="")
{
?>
                <li class="control">

                    <input type="checkbox" name="check_seller_form" id="check_seller_form" onclick="checkSellerFormRequired(this.checked)" title="<?php echo $this->__('Want To Sell Products?') ?>" class="checkbox" />

                    <label for="check_seller_form"><?php echo $this->__('Want To Sell Products?') ?></label>

                </li>
<?php } ?>
   <?php endif ?>
                <?php else:?>

                <li class="control">

                    <input type="checkbox" name="check_seller_form" id="check_seller_form" onclick="checkSellerFormRequired(this.checked)" title="<?php echo $this->__('Want To Edit Seller Profile?') ?>" class="checkbox" checked/>

                    <label for="check_seller_form"><?php echo $this->__('Want To Edit Seller Profile?') ?></label>

                    <input type="hidden" name="is_seller_subscribe" value="<?php echo $isSeller; ?>" id="is_seller_subscribe">

                </li>

                <?php endif;?> 

            <?php endif;?>

        </ul>

    </div>

    <?php if($isMarketplaceEnabled):?>
<input type="hidden" name="company_name" id="company_name" value="<?php echo $this->htmlEscape($this->getCustomer()->getCompanyName()) ?>" title="<?php echo $this->__('Company Name') ?>" class="input-text " />
<input type="hidden" name="company_locality" id="company_locality" value="noaddress" title="<?php echo $this->__('Company Locality') ?>" class="input-text " />

        <!-- add/edit seller form -->

       <div id="seller_form" class="fieldset" style="<?php if($isSeller == 1): echo 'display:blobk'; else: echo 'display:none'; endif;?>">

            <h2 class="legend"><?php if($isSeller == 1): echo $this->__('Edit Seller Profile'); else: echo $this->__('Add Seller Profile'); endif; ?></h2>

            <ul class="form-list">

              <!--  <li>

                    <label  class="required"><?php echo $this->__('Company Banner').' ('. Mage::getStoreConfig('marketplace/marketplace/default_width'). $this->__('pixel'). ' X '. Mage::getStoreConfig('marketplace/marketplace/default_height') . $this->__('pixel') . ')'; ?></label>

                    <div class="input-box"> 

                      <?php $banner = $this->getCustomer()->getCompanyBanner(); ?>                  

                      <img src="<?php echo $banner; ?>" />                

                      <input type="file" id="company_banner" size="20" name="company_banner">

                      <input type="hidden" name="old_banner" value="<?php echo $banner; ?>" id="old_banner">

                    </div>

                </li>

                <li>

                    <label  class="required"><?php echo $this->__('Company Logo').' ('. Mage::getStoreConfig('marketplace/marketplace/default_logo_width'). $this->__('pixel'). ' X '. Mage::getStoreConfig('marketplace/marketplace/default_logo_height'). $this->__('pixel') . ')'; ?></label>

                    <div class="input-box">  

                    <?php $logo = $this->getCustomer()->getCompanyLogo(); ?>

                      <img src="<?php echo $logo; ?>" />                     

                    <input type="file" id="company_logo" size="20" name="company_logo">

                    <input type="hidden" name="old_logo" value="<?php echo $logo; ?>" id="old_logo">

                    </div>

                </li>

                <li>

                    <label  class="required"> <em>*</em><?php echo $this->__('Company Name') ?></label>

                    <div class="input-box">

                    <input type="text" name="company_name" id="company_name" value="<?php echo $this->htmlEscape($this->getCustomer()->getCompanyName()) ?>" title="<?php echo $this->__('Company Name') ?>" class="input-text " />

                    </div>

                </li>

                <li>

                    <label  class="required"><em>*</em><?php echo $this->__('Company Locality') ?></label>

                    <div class="input-box">

                    <input type="text" name="company_locality" id="company_locality" value="<?php echo $this->htmlEscape($this->getCustomer()->getCompanyLocality()) ?>" title="<?php echo $this->__('Company Locality') ?>" class="input-text " />

                    </div>

                </li> -->

                <li>

                    <label  class="required"><?php echo $this->__('Bio') ?></label>

                    <div class="input-box">

                       <textarea name="company_description" cols="40" id="company_description" title="<?php echo $this->__('Company Description')?>"><?php echo $this->htmlEscape($this->getCustomer()->getCompanyDescription())?></textarea>

                    </div>

                </li>

            </ul>

        </div>

    <?php endif;?>

    <!-- End of edit seller form -->

    <div class="fieldset" style="display:none;">

        <h2 class="legend"><?php echo $this->__('Change Password') ?></h2>

        <ul class="form-list">

            <li>

                <label for="current_password" class="required"><em>*</em><?php echo $this->__('Current Password') ?></label>

                <div class="input-box">

                    <!-- This is a dummy hidden field to trick firefox from auto filling the password -->

                    <input type="text" class="input-text no-display" name="dummy" id="dummy" />

                    <input type="password" title="<?php echo $this->__('Current Password') ?>" class="input-text" name="current_password" id="current_password" />

                </div>

            </li>

            <li class="fields">

                <div class="field">

                    <label for="password" class="required"><em>*</em><?php echo $this->__('New Password') ?></label>

                    <div class="input-box">

                        <input type="password" title="<?php echo $this->__('New Password') ?>" class="input-text validate-password" name="password" id="password" />

                    </div>

                </div>

                <div class="field">

                    <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm New Password') ?></label>

                    <div class="input-box">

                        <input type="password" title="<?php echo $this->__('Confirm New Password') ?>" class="input-text validate-cpassword" name="confirmation" id="confirmation" />

                    </div>

                </div>

            </li>

        </ul>

    </div>
    
    
    
    
    <?php if (Mage::getSingleton('customer/session')->isLoggedIn()==0): ?>

<?php else: ?>
<?php
				$customer = Mage::getSingleton('customer/session')->getCustomer();
 $zz=   $customer->getCompanyName(); // Full Name
if($zz=="")
{
?>
<ul>
<li><a href="http://gemz.gallery/index.php/review/customer/">My Product Reviews</a></li>
<li><a href="http://gemz.gallery/index.php/wishlist/">My Wishlist</a></li>
</ul>

<?php } ?>
   <?php endif ?>
    
    
    
    
    
    

    <div class="buttons-set">

        <p class="required"><?php echo $this->__('* Required Fields') ?></p>

        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>

        <button type="submit" title="<?php echo $this->__('Save') ?>" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>

    </div>

</form>

<script type="text/javascript">

//<![CDATA[

    var dataForm = new VarienForm('form-validate', true);

    function setPasswordForm(arg){

        if(arg){

            $('current_password').up(3).show();

            $('current_password').addClassName('required-entry');

            $('password').addClassName('required-entry');

            $('confirmation').addClassName('required-entry');



        }else{

            $('current_password').up(3).hide();

            $('current_password').removeClassName('required-entry');

            $('password').removeClassName('required-entry');

            $('confirmation').removeClassName('required-entry');

        }

    }

    

    /**

    *Check  checkbox is cheked or no,if yes then display seller form

    *else hide form and remove validations

    **/

    function checkSellerFormRequired(arg){

        if(arg){        

            $('seller_form').show();

            $('company_name').addClassName('required-entry');

            $('company_locality').addClassName('required-entry');



        }else{        

            $('seller_form').hide();

            $('current_password').removeClassName('required-entry');

            $('company_name').removeClassName('required-entry');

            $('company_locality').removeClassName('required-entry');

        }

    }     

    <?php if($this->getCustomer()->getChangePassword()): ?>

        setPasswordForm(true);

    <?php endif; ?>

//]]>

</script>