<?php

/**

 * Cybage Marketplace Plugin

 *

 * NOTICE OF LICENSE

 *

 * This source file is subject to the Open Software License (OSL 3.0)

 * It is available on the World Wide Web at:

 * http://opensource.org/licenses/osl-3.0.php

 * If you are unable to access it on the World Wide Web, please send an email

 * To: Support_Magento@cybage.com.  We will send you a copy of the source file.

 *

 * @category   Marketplace Plugin

 * @package    Cybage_Marketplace

 * @copyright  Copyright (c) 2014 Cybage Software Pvt. Ltd., India

 *             http://www.cybage.com/pages/centers-of-excellence/ecommerce/ecommerce.aspx

 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)

 * @author     Cybage Software Pvt. Ltd. <Support_Magento@cybage.com>

 */

?>

<div class="account-create">

    <div class="page-title">

        <h1><?php echo $this->__('Create an Account') ?></h1>

    </div>

    <?php echo $this->getChildHtml('form_fields_before')?>

    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate" enctype="multipart/form-data">

        <div class="fieldset">

            <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />

            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />

            <h2 class="legend"><?php echo $this->__('Personal Information') ?></h2>

            <ul class="form-list">

                <li class="fields">

                    <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>

                </li>

                <li>

                    <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>

                    <div class="input-box">

                        <input type="text" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />

                    </div>

                </li>
            

                <?php if ($this->isNewsletterEnabled()): ?>

               <!-- <li class="control">

                    <div class="input-box">

                        <input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" />

                    </div>

                    <label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>

                </li>-->

                <?php endif ?>

                <?php $isMarketplaceEnabled=Mage::Helper("marketplace")->isMarketplaceEnabled(); ?>

                <?php if($isMarketplaceEnabled):?>

                <li class="control">

                  <input type="checkbox" name="check_seller_form" id="check_seller_form" onclick="checkSellerFormRequired(this.checked)" title="<?php echo $this->__('Want To Sell Products?') ?>" class="checkbox" <?php if ($this->escapeHtml($this->getFormData()->getCheckSellerForm())) { echo 'checked'; } ?> />

                  <label for="check_seller_form"><?php echo $this->__('Want To Sell Products?') ?></label>

                </li>

                <?php endif;?>

            <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>

            <?php if ($_dob->isEnabled()): ?>

                <li><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>

            <?php endif ?>

            <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>

            <?php if ($_taxvat->isEnabled()): ?>

                <li><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>

            <?php endif ?>

            <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>

            <?php if ($_gender->isEnabled()): ?>

                <li><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>

            <?php endif ?>

            </ul>

        </div>        

    <?php if($isMarketplaceEnabled):?>

    <!--End of Add seller profile form-->

   <div id="seller_form" class="fieldset" style="<?php if ($this->escapeHtml($this->getFormData()->getCheckSellerForm())) { echo 'display:block;'; } else { echo 'display:none;'; } ?>">

     <!--        <h2 class="legend"><?php echo $this->__('Seller Profile') ?></h2>

            <ul class="form-list">

              <li>

                <label  class="required"><?php echo $this->__('Company Banner').' ('.Mage::getStoreConfig('marketplace/marketplace/default_width').' pixel X '.Mage::getStoreConfig('marketplace/marketplace/default_height').' pixel)'; ?></label>

                <div class="input-box">

                <input type="file" id="company_banner" size="20" name="company_banner">

                </div>

              </li>

              <li>

                <label  class="required"><?php echo $this->__('Company Logo').' ('. Mage::getStoreConfig('marketplace/marketplace/default_logo_width'). $this->__('pixel'). ' X '. Mage::getStoreConfig('marketplace/marketplace/default_logo_height'). $this->__('pixel') . ')'; ?></label>

                <div class="input-box">

                <input type="file" id="company_logo" size="20" name="company_logo">

                </div>

            </li> -->

            <li>

                <label  class="required"> <em>*</em><?php echo $this->__('Profile  Name') ?></label>

                <div class="input-box">

                <input type="text" name="company_name" id="company_name"  title="<?php echo $this->__('Profile  Name') ?>" class="input-text required-entry" value="<?php echo $this->escapeHtml($this->getFormData()->getCompanyName()) ?>" />

                </div>

            </li>
                <li>

                <label  class="required"><?php echo $this->__('Bio') ?></label>

                <div class="input-box">

                    <textarea name="company_description" cols="40" id="company_description" title="<?php echo $this->__('Company Description') ?>" class="required-entry"><?php echo $this->escapeHtml($this->getFormData()->getCompanyDescription()) ?></textarea>

                </div>

            </li>

           <!-- <li>

                <label  class="required"><em>*</em><?php echo $this->__('Company Locality') ?></label>

                <div class="input-box">

                <input type="text" name="company_locality" id="company_locality"  title="<?php echo $this->__('Company Locality') ?>" class="input-text required-entry" value="<?php echo $this->escapeHtml($this->getFormData()->getCompanyLocality()) ?>" />

                </div>

            </li>

        

            </ul>-->

        </div>

    <?php endif;?>

    <?php if($this->getShowAddressFields()): ?>

        <div class="fieldset">

            <input type="hidden" name="create_address" value="1" />

            <h2 class="legend"><?php echo $this->__('Address Information') ?></h2>

            <ul class="form-list">

                <li class="fields">

                    <div class="field">

                        <label for="company"><?php echo $this->__('Company') ?></label>

                        <div class="input-box">

                            <input type="text" name="company" id="company" value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />

                        </div>

                    </div>

                    <div class="field">

                        <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>

                        <div class="input-box">

                            <input type="text" name="telephone" id="telephone" value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" />

                        </div>

                    </div>

                </li>

            <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>

                <li class="wide">

                    <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>

                    <div class="input-box">

                        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />

                    </div>

                </li>

            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>

            <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>

                <li class="wide">

                    <div class="input-box">

                        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $_streetValidationClass ?>" />

                    </div>

                </li>

            <?php endfor; ?>

                <li class="fields">

                    <div class="field">

                        <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>

                        <div class="input-box">

                            <input type="text" name="city" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>" title="<?php echo $this->__('City') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />

                        </div>

                    </div>

                    <div class="field">

                        <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>

                        <div class="input-box">

                            <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">

                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>

                            </select>

                            <script type="text/javascript">

                            //<![CDATA[

                                $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");

                            //]]>

                            </script>

                            <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />

                        </div>

                    </div>

                </li>

                <li class="fields">

                    <div class="field">

                        <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>

                        <div class="input-box">

                            <input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />

                        </div>

                    </div>

                    <div class="field">

                        <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>

                        <div class="input-box">

                            <?php echo $this->getCountryHtmlSelect() ?>

                        </div>

                    </div>

                </li>

            </ul>

            <input type="hidden" name="default_billing" value="1" />

            <input type="hidden" name="default_shipping" value="1" />

        </div>

    <?php endif; ?>

        <div class="fieldset">

            <h2 class="legend"><?php echo $this->__('Login Information') ?></h2>

            <ul class="form-list">

                <li class="fields">

                    <div class="field">

                        <label for="password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>

                        <div class="input-box">

                            <input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />

                        </div>

                    </div>

                    <div class="field">

                        <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>

                        <div class="input-box">

                            <input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" />

                        </div>

                    </div>

                </li>

                <?php echo $this->getChildHtml('form.additional.info'); ?>

                <?php echo $this->getChildHtml('persistent.remember.me'); ?>

            </ul>

            <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>

        </div>

        <div class="buttons-set">

            <p class="required"><?php echo $this->__('* Required Fields') ?></p>

            <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="back-link"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>

            <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>

        </div>

        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>

            <input name="context" type="hidden" value="checkout" />

        <?php endif; ?>

    </form>

    <script type="text/javascript">
	 jQuery(document).ready(function(){
		 jQuery(".closepopup").click(function () {
			 jQuery('.blackoverlay,#showterms').hide();
			   jQuery('#chk').attr('checked', false);
			  jQuery('#check_seller_form').attr('checked', false);
		 });
		 
	jQuery('#showterms').hide();
	});
	jQuery("#chk").live("click", function () {
        if (jQuery("#chk").is(":checked")) {
          jQuery('#showterms').hide();
		  jQuery('#seller_form').show();
		   jQuery('.blackoverlay,#showterms').hide();
		 
		  //jQuery('#seller_form').hide();
		   //jQuery('#check_seller_form').attr('checked', false);
        } else {
             
			 jQuery('#showterms').show();
			 jQuery('#seller_form').hide();
			 jQuery('#check_seller_form').attr('checked', false);
        }
    });
jQuery("#check_seller_form").live("click", function () {
        if (jQuery("#check_seller_form").is(":checked")) {
          jQuery('#showterms').show();
		 jQuery('#seller_form').hide();
		  jQuery('.blackoverlay').show();
           jQuery('#chk').attr('checked', false);
		   //jQuery('#check_seller_form').attr('checked', false);
        } else {
            // jQuery('#seller_form').hide();
			 jQuery('#showterms').hide();
        }
    });

    //<![CDATA[

        var dataForm = new VarienForm('form-validate', true);



    /**

     * Check  checkbox is cheked or no,if yes then display seller form

     * else hide form and remove validations

     **/

    function checkSellerFormRequired(arg){

        if(arg){

            $('seller_form').show();

            $('company_name').addClassName('required-entry');

            $('company_locality').addClassName('required-entry');

        }else{

            $('seller_form').hide();

            //$('current_password').removeClassName('required-entry');

           // $('company_name').removeClassName('required-entry');

            //$('company_locality').removeClassName('required-entry');

        }

    }

    <?php if($this->getShowAddressFields()): ?>

    new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');

    <?php endif; ?>

    //]]>

    </script>

</div>