<?php
/**
 * Cybage Marketplace Plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * It is available on the World Wide Web at:
 * http://opensource.org/licenses/osl-3.0.php
 * If you are unable to access it on the World Wide Web, please send an email
 * To: Support_Magento@cybage.com.  We will send you a copy of the source file.
 *
 * @category   Marketplace Plugin
 * @package    Cybage_Marketplace
 * @copyright  Copyright (c) 2014 Cybage Software Pvt. Ltd., India
 *             http://www.cybage.com/pages/centers-of-excellence/ecommerce/ecommerce.aspx
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Cybage Software Pvt. Ltd. <Support_Magento@cybage.com>
 */
echo $this->getMessagesBlock()->getGroupedHtml();
?>
<?php $_orderCollection = Mage::getModel('marketplace/marketplace')->getLastFewOrder();?>
<div class="dashboard">
    <div class="marketplace-account box-recent">
        <h2><?php echo $this->__('Products Ordered') ?></h2>
        <?php  if($_orderCollection->getSize()): ?>
            <table class="data-table">
                <thead>                    
                    <tr>
                    <th><?php echo $this->__('Product name') ?></th>
                    <th><?php echo $this->__('Quantity Ordered') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($_orderCollection as $order): ?>
                        <tr>
                        <td><span class="nobr"><?php echo  $order->getName(); ?></span></td>
                        <td><span class="nobr"><?php echo  $order->getQtyOrdered()*1;?></span></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        <?php else: ?>
        <p>
            <?php echo $this->__('You have no products.'); ?>
        </p>
        <?php endif?>
    </div>
</div>