<?php
/**
 * Cybage Marketplace Plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * It is available on the World Wide Web at:
 * http://opensource.org/licenses/osl-3.0.php
 * If you are unable to access it on the World Wide Web, please send an email
 * To: Support_Magento@cybage.com.  We will send you a copy of the source file.
 *
 * @category   Marketplace Plugin
 * @package    Cybage_Marketplace
 * @copyright  Copyright (c) 2014 Cybage Software Pvt. Ltd., India
 *             http://www.cybage.com/pages/centers-of-excellence/ecommerce/ecommerce.aspx
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Cybage Software Pvt. Ltd. <Support_Magento@cybage.com>
 */

$_items = $this->getReviewsCollection();
?>
<div class="box-collateral box-reviews" id="customer-reviews">
    <?php if (count($_items)):?>
        <h2><?php echo $this->__('Customer Reviews') ?></h2>
        <?php echo $this->getPagerHtml() ?>
        <dl>
        <?php foreach ($_items as $_review):?>
            <dt>
                <a href="<?php echo $this->getReviewUrl($_review->getId()) ?>"><?php echo $this->htmlEscape($_review->getTitle()) ?></a> <?php echo $this->__('Review by <span>%s</span>', $this->htmlEscape($_review->getNickname())) ?>
            </dt>
                <div class="review_product_name">
                <?php $catalogModel = Mage::getModel('catalog/product')->load($_review->getEntityPkValue());
                echo $this->__('Product Name :').'&nbsp &nbsp '.$this->__($catalogModel->getName());
                ?>
            </div>
            <dd>
                <?php 
                $_votes = $this->getRatingInfo($_review); 
                ?>
                <?php if (count($_votes)): ?>
                <table class="ratings-table">
                    <col width="1" />
                    <col />
                    <tbody>
                        <?php foreach ($_votes as $_vote): ?>
                        <tr>
                            <th><?php echo $this->escapeHtml($_vote->getRatingCode()) ?></th>
                            <td>
                                <div class="rating-box">
                                    <div class="rating" style="width:<?php echo $_vote->getPercent() ?>%;"></div>
                                </div>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <?php endif; ?>
                <?php echo nl2br($this->htmlEscape($_review->getDetail())) ?>
                <small class="date"><?php echo $this->__('(Posted on %s)', $this->formatDate($_review->getCreatedAt()), 'long') ?></small>
            </dd>
        <?php endforeach; ?>
        </dl>
        <?php echo $this->getPagerHtml() ?>
    <?php else:?>
        <?php $sellerId = $this->getRequest()->getParam('seller_id'); ?>
        <?php if(!empty($sellerId)): ?>           
        <div><?php echo $this->__('Reviews not found'); ?></div>
        <?php else:?>
        <div><?php echo $this->__('Seller id is null'); ?></div>        
        <?php endif;?> 
    <?php endif;?>
</div>