<?php
/**
 * Cybage Marketplace Plugin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * It is available on the World Wide Web at:
 * http://opensource.org/licenses/osl-3.0.php
 * If you are unable to access it on the World Wide Web, please send an email
 * To: Support_Magento@cybage.com.  We will send you a copy of the source file.
 *
 * @category   Marketplace Plugin
 * @package    Cybage_Marketplace
 * @copyright  Copyright (c) 2014 Cybage Software Pvt. Ltd., India
 *             http://www.cybage.com/pages/centers-of-excellence/ecommerce/ecommerce.aspx
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Cybage Software Pvt. Ltd. <Support_Magento@cybage.com>
 */


?>
<?php /* ?>
<?php if (!empty($seller['company_logo'])):?>
<div class="customer-logo">
    <img src="<?php echo $seller['company_logo'];?>" width ="195px" height="225px"/>
</div>
<?php endif;?>
<?php */ ?>

<div class="profileimage-wrapper">
    <div class="left">
        <div class="userinfo">
            <strong><a href="<?php echo Mage::getUrl('customer/account'); ?>">&nbsp;</a> <?php
                $seller = $this->getSellerData();
                echo $seller['firstname'] . " " . $seller['lastname'];

                ?></strong>

            <div class="profilepic">
                <img src="<?php echo $this->getProfileImage(); ?>" alt="" />
            </div>
            <strong> About the Designer:</strong>

            <div class="info">
                <?php echo $seller['company_description']; ?>
            </div>
        </div>
    </div>
    <div class="clear"></div>
    <div class="social">
        <span><strong>SHARE:</strong></span>
        <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-54ca55585e6c1051"
                async="async"></script>
        <div class="addthis_custom_sharing"></div>
    </div>
</div>
