<div class="chic latest-product">
    <h2 class="title text-center col-md-6">Chic</h2>

    <div class="owl-carousel owl-carousels no-carousel">

        <?php
        $_helper = $this->helper('catalog/output');
        $storeId = Mage::app()->getStore()->getId();
        $catalog = $this->getLayout()->createBlock('catalog/product_list')->setStoreId($storeId);
        $collection = Mage::getModel('catalog/product')->getCollection();
        $collection->addAttributeToSelect('*');
        $collection->addFieldToFilter(array(
            array('attribute' => 'chic', 'eq' => true),
        ));
        $collection->addAttributeToFilter('status', 1);
        $collection->setPageSize(11)->setCurPage(1);
        ?>
        <?php if (!$collection->count()) : ?>
            <p class="note-msg"><?php echo $this->__('There are no new products at the moment.') ?></p>
        <?php else : ?>
            <?php
            $iCollection = 1;
            foreach ($collection as $_product) : ?>
                <?php if ($iCollection == 6) : ?>
                <div class="item fili">
                    <div class="products">
                        <a href="<?php echo $this->getBaseUrl() ?>marketplace/KOKKU.html" title="<?php echo $this->__('Yes We Speak Filigree') ?>">
                            <img src="<?php echo $this->getSkinUrl('images/home/fili.jpg') ?>" alt="" />
                        </a>
                    </div>
                </div>
                <?php endif; ?>
                <div class="item">
                    <div class="products">


                        <a class="product-image" href="<?php echo $_product->getProductUrl() ?>"
                           title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"><img
                                src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(true)->keepAspectRatio(true)->keepFrame(false)->resize(210, null); ?>"
                                alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/></a>


                        <h2 class="product-name"><a
                                href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a>
                        </h2>

                        <div class="show-desc">


                            <div
                                class="pro-desc"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>


                            <div class="price-box">
                                <div class="regular-price">
                                    <div
                                        class="price"><?php echo Mage::helper('core')->currency($_product->getPrice(), true, false); ?></div>
                                </div>
                            </div>

                        </div>
                        <?php
                        // Get the Special Price
                        $specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice();
                        // Get the Special Price FROM date
                        $specialPriceFromDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialFromDate();
                        // Get the Special Price TO date
                        $specialPriceToDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialToDate();

                        $newToDate = Mage::getModel('catalog/product')->load($_product->getId())->getNewsToDate();
                        // Get Current date
                        $today = time();

                        if ($specialprice) {

                            if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) {
                                // echo '<span class="sale-product">Sale</span>';
                            }
                        }
                        if ($today <= strtotime($newToDate)) {
                            //echo '<span class="new-product"><b>New</b></span>';
                        }
                        ?>



                        <?php if (Mage::getSingleton('customer/session')->isLoggedIn() == 0): ?>
                            <?php
                            $_url = Mage::helper('checkout/cart')->getAddUrl($_product);

                            ?>
                            <?php if ($_product->isSaleable()): ?>
                                <button class="add2cart btn-cart button"
                                        onclick="setLocation('<?= $_url ?>')"><?= __('Add to Cart') ?></button>
                                <!--	 <a class="add2cart" href="" onclick="setLocation('<?= $_url ?>')"><img src="<?php echo $this->getSkinUrl() ?>/images/cart.png"></a>-->
                            <?php endif; ?>

                            <!--  <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocationAjax('<?php echo $_url ?>','<?php echo $_product->getId() ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
				   <span id='ajax_loader<?php echo $_product->getId() ?>' style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>'/></span>-->


                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <a class="add2wishlist"
                                   href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"><img
                                        src="<?php echo $this->getSkinUrl() ?>images/addfavorite.png"></a>
                            <?php endif; ?>
                        <?php else: ?>
                            <?php
                            $customer = Mage::getSingleton('customer/session')->getCustomer();
                            $zz = $customer->getCompanyDescription(); // Full Name
                            if ($zz == "") :
                            ?>
                                <?php
                                $_url = Mage::helper('checkout/cart')->getAddUrl($_product);

                                ?>
                                <?php if ($_product->isSaleable()): ?>
                                    <button class="add2cart btn-cart button"
                                            onclick="setLocation('<?= $_url ?>')"><?= __('Add to Cart') ?></button>
                                    <!--	 <a class="add2cart" href="" onclick="setLocation('<?= $_url ?>')"><img src="<?php echo $this->getSkinUrl() ?>/images/cart.png"></a>-->
                                <?php endif; ?>

                                <!--  <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocationAjax('<?php echo $_url ?>','<?php echo $_product->getId() ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
				   <span id='ajax_loader<?php echo $_product->getId() ?>' style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>'/></span>-->


                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <a class="add2wishlist"
                                       href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"><img
                                            src="<?php echo $this->getSkinUrl() ?>images/addfavorite.png"></a>
                                <?php endif; ?>
                            <?php endif; ?>
                        <?php endif ?>
                    </div>
                </div>
            <?php $iCollection++; endforeach; ?>
        <?php endif ?>
    </div>
    <div class="clear">&nbsp;</div>
</div>


