<div id="our-designers" class="fluid-container">
    <!--
    <h1 class="title text-center">
        <?php //echo $this->__('Meet some of our designers') ?>
    </h1>
    -->
    <div class="row">
        <div class="col-md-6 designer">
            <a href="<?php echo $this->getBaseUrl() ?>marketplace/Irit-Design.html" title="<?php echo $this->__('Irit Design') ?>">
                <img src="<?php echo $this->getSkinUrl('images/home/irit.jpg') ?>" alt="" />
            </a>
        </div>
        <div class="col-md-6 designer">
            <a href="<?php echo $this->getBaseUrl() ?>marketplace/Jude-Frances.html" title="<?php echo $this->__('Jude Frances') ?>">
                <img src="<?php echo $this->getSkinUrl('images/home/des.jpg') ?>" alt="" />
            </a>
        </div>
    </div>
    <div class="row featured-links">
        <div class="col-xs-4">
            <a href="<?php echo $this->getBaseUrl() ?>marketplace/KOKKU.html" title="<?php echo $this->__('Yes We Speak Filigree') ?>">
                <img src="<?php echo $this->getSkinUrl('images/home/fili.jpg') ?>" alt="" />
            </a>
        </div>
        <div class="col-xs-4">
            <a href="#" title="<?php echo $this->__('Let\'s KISS') ?>">
                <img src="<?php echo $this->getSkinUrl('images/home/kiss.jpg') ?>" alt="" />
            </a>
        </div>
        <div class="col-xs-4">
            <a href="<?php echo $this->getBaseUrl() ?>marketplace/Madstone-Design.html" title="<?php echo $this->__('New to GEMZ') ?>">
                <img src="<?php echo $this->getSkinUrl('images/home/hello.jpg') ?>" alt="" />
            </a>
        </div>
    </div>
</div>