<!--<div class="latest-product popular">
<h1 class="title">Popular</h1>
<div class="owl-carousels">
	<div class="item">
    	<div class="products"><a href="javascript:;" class="product-image"><img src="http://gemz.gallery/media/catalog/product/cache/1/small_image/250x200/9df78eab33525d08d6e5fb8d27136e95/e/a/earring.jpg" ></a></div>
    </div>
    <div class="item">
    	<div class="products"><a href="javascript:;" class="product-image"><img src="http://gemz.gallery/media/catalog/product/cache/1/small_image/250x200/9df78eab33525d08d6e5fb8d27136e95/3/9/39968_824.jpg" ></a></div>
    </div>
    <div class="item">
    	<div class="products"><a href="javascript:;" class="product-image"><img src="http://gemz.gallery/media/catalog/product/cache/1/small_image/250x200/9df78eab33525d08d6e5fb8d27136e95/c/a/canstockphoto19820321.jpg" ></a></div>
    </div>
    
    
    <div class="clear"></div>
</div>
</div>-->


<!--<div class="featured-product popular classic">
<h1 class="title">Classic</h1>
<div class="owl-carousels no-carousel">
	<div class="item">
    	<div class="products"><a href="javascript:;" class="product-image"><img src="http://gemz.gallery/media/catalog/product/cache/1/small_image/9df78eab33525d08d6e5fb8d27136e95/c/a/canstockphoto8315679.jpg" ></a></div>
    </div>
    <div class="item">
    	<div class="products"><a href="javascript:;" class="product-image"><img src="http://gemz.gallery/media/catalog/product/cache/1/small_image/9df78eab33525d08d6e5fb8d27136e95/d/i/diamodn_earrings.jpg" ></a></div>
    </div>
    <div class="item">
    	<div class="products"><a href="javascript:;" class="product-image"><img src="http://gemz.gallery/media/catalog/product/cache/1/small_image/9df78eab33525d08d6e5fb8d27136e95/c/a/canstockphoto5623565_1.jpg" ></a></div>
    </div>
    
     <div class="item">
    	<div class="products"><a href="javascript:;" class="product-image"><img src="http://gemz.gallery/media/catalog/product/cache/1/small_image/9df78eab33525d08d6e5fb8d27136e95/c/a/canstockphoto11252436_2.jpg" ></a></div>
    </div>
    
    
    <div class="clear"></div>
</div>
</div>-->

<div class="chic-hot">

<?php 
echo $this->getLayout()->createBlock('cms/block')->setBlockId('hot')->toHtml(); 
echo $this->getLayout()->createBlock('cms/block')->setBlockId('chic')->toHtml(); 
?>
    
  

</div>





