<div class="recent-purchase">
     <h1 class="title">RECENTLY PURCHASED</h1>


                <ul>
            
                        <?php

    $orders = Mage::getResourceModel('sales/order_collection')
                        ->addFieldToSelect('*')
                        ->setOrder('entity_id', 'desc');  
   foreach($orders as $order){
    $collection = $order->getAllVisibleItems();
   ?>
   <?php if (!$collection) : ?>
    <p class="note-msg"><?php echo $this->__('There are no new products at the moment.') ?></p>
   <?php else : ?>
       <?php foreach ($collection as $_product) :
       $_product = Mage::getModel('catalog/product')->setStoreId($storeId)->load($_product->getId());
    ?>
    <?php if($_product->getStatus()==1): ?>
    <li>
    <div class="products">
    

 <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(200,150); ?>"  alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
          
                      
                  <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->htmlEscape($_product->getName())?></a></h2>
<div class="pro-desc"><?php echo $_product->getShortDescription(); ?></div>
             
             
      <?php 
    // Get the Special Price
    $specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice(); 
    // Get the Special Price FROM date
   $specialPriceFromDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialFromDate();
    // Get the Special Price TO date
   $specialPriceToDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialToDate();
   
   $newToDate = Mage::getModel('catalog/product')->load($_product->getId())->getNewsToDate();
    // Get Current date
    $today =  time();
 
    if ($specialprice){
        
        if($today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate)) {
      //  echo '<span class="sale-product">Sale</span>';
      }
      }
       if($today <= strtotime($newToDate)) {
        //echo '<span class="new-product"><b>New</b></span>';
      }
?>       


<?php if (Mage::getSingleton('customer/session')->isLoggedIn()==0): ?>
<?php 
				   $_url = Mage::helper('checkout/cart')->getAddUrl($_product);
				   
				   ?>
 <?php if($_product->isSaleable()):?>
              <button class="add2cart btn-cart button" onclick="setLocation('<?=$_url?>')"><?=__('Add to Cart')?></button>
		<!--	 <a class="add2cart" href="" onclick="setLocation('<?=$_url?>')"><img src="<?php echo $this->getSkinUrl()?>/images/cart.png"></a>-->
                   <?php endif;?>
				   
				 <!--  <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocationAjax('<?php echo $_url ?>','<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
				   <span id='ajax_loader<?php echo $_product->getId()?>' style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>'/></span>-->

                
                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                        <a class="add2wishlist" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"><img src="<?php echo $this->getSkinUrl()?>images/addfavorite.png"></a>
                        <?php endif; ?>   
<?php else: ?>
<?php
				$customer = Mage::getSingleton('customer/session')->getCustomer();
$zz=   $customer->getCompanyDescription(); // Full Name
if($zz=="")
{
?>

  
<?php 
				   $_url = Mage::helper('checkout/cart')->getAddUrl($_product);
				   
				   ?>
 <?php if($_product->isSaleable()):?>
              <button class="add2cart btn-cart button" onclick="setLocation('<?=$_url?>')"><?=__('Add to Cart')?></button>
		<!--	 <a class="add2cart" href="" onclick="setLocation('<?=$_url?>')"><img src="<?php echo $this->getSkinUrl()?>/images/cart.png"></a>-->
                   <?php endif;?>
				   
				 <!--  <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocationAjax('<?php echo $_url ?>','<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
				   <span id='ajax_loader<?php echo $_product->getId()?>' style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>'/></span>-->

                
                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                        <a class="add2wishlist" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"><img src="<?php echo $this->getSkinUrl()?>images/addfavorite.png"></a>
                        <?php endif; ?>    
			
			

<?php

}
?>
   <?php endif ?>  
    </div>
   
                  
             
                   
             </li>
             
             <?php endif; ?>
             
          <?php endforeach; ?>
     
       <div class="cls"></div>
   <?php endif;
   
   }
   ?>
                          
       </ul>
               
</div>

<style>

</style>
